/**********************************************************
Font generated by the LCD Vision V1.00 font editor
(C) Copyright 2011 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

Font name: Courier
Fixed font width: 7 pixels
Font height: 14 pixels
First character: 0x20
Last character: 0x7F
**********************************************************/

#ifndef _COURIER7X14_INCLUDED_
#define _COURIER7X14_INCLUDED_

extern flash unsigned char courier7x14[];

#endif

