/**********************************************************
Font generated by the LCD Vision V1.00 font editor
(C) Copyright 2011 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

Font name: Courier Bold
The font is proportional (has variable width).
Font height: 14 pixels
First character: 0x20
Last character: 0x7F
**********************************************************/

#ifndef _COURIER_BOLD14_INCLUDED_
#define _COURIER_BOLD14_INCLUDED_

extern flash unsigned char courier_bold14[];

#endif

