/**********************************************************
Font generated by the LCD Vision V1.00 font editor
(C) Copyright 2011 Pavel Haiduc, HP InfoTech s.r.l.
http://www.hpinfotech.com

Font name: Script
The font is proportional (has variable width).
Font height: 19 pixels
First character: 0x20
Last character: 0x7F
**********************************************************/

#ifndef _SCRIPT19_INCLUDED_
#define _SCRIPT19_INCLUDED_

extern flash unsigned char script19[];

#endif

